// questions.js
// Banque de questions sur le quotidien. Ajoute/retire des lignes ici
// pour faire évoluer la banque sans toucher au reste du code.

var QUESTIONS = [
  "Quelle est la première chose que tu fais en te réveillant ?",
  "À quelle heure de la journée es-tu le plus en forme ?",
  "Quel petit rituel du matin tu ne sautes jamais ?",
  "Quel est ton plat préféré quand tu manques de temps pour cuisiner ?",
  "Quelle habitude aimerais-tu enfin adopter cette année ?",
  "Comment tu te déplaces le plus souvent au quotidien ?",
  "Quel bruit du quotidien te dérange le plus ?",
  "Quel est ton moment préféré de la journée, et pourquoi ?",
  "Qu'est-ce qui te fait toujours sourire, même un mauvais jour ?",
  "Quelle appli regardes-tu le plus sur ton téléphone chaque jour ?",
  "Si tu avais une heure de libre en plus par jour, tu en ferais quoi ?",
  "Quel est le dernier truc qui t'a fait rire aujourd'hui ?",
  "Quelle est ta boisson du quotidien : café, thé, jus, ou autre chose ?",
  "Quel est ton snack préféré pour tenir l'après-midi ?",
  "Qu'est-ce qui te motive à sortir du lit le matin ?",
  "Quelle chanson tu écoutes en boucle en ce moment ?",
  "Comment tu décompresses après une journée chargée ?",
  "Quel est ton endroit préféré dans ta ville pour te poser ?",
  "Quelle est la dernière chose que tu as apprise sur toi-même ?",
  "Quel petit plaisir tu t'offres après une bonne journée ?",
  "Quelle est ta manière préférée de passer un dimanche ?",
  "Qu'est-ce que tu fais en premier quand tu rentres chez toi ?",
  "Quel est ton moyen de transport préféré, et pourquoi ?",
  "Quelle est la tâche du quotidien que tu détestes le plus ?",
  "Quel est ton repas préféré de la journée : petit-déj, déjeuner ou dîner ?",
  "Quelle habitude de ton entourage t'inspire au quotidien ?",
  "Quel est le dernier message qui t'a fait plaisir aujourd'hui ?",
  "Quelle activité te fait complètement oublier le temps qui passe ?",
  "Quel est ton juron ou ton mot préféré quand ça ne va pas ?",
  "Comment s'appelle la personne que tu appelles en premier quand il y a une bonne nouvelle ?",
  "Quel est ton objectif du jour, même tout petit ?",
  "Quel bruit ou odeur te rappelle immédiatement chez toi ?",
  "Quelle est la dernière série ou vidéo que tu as regardée ?",
  "Quel est ton talent caché que peu de gens connaissent ?",
  "Quelle est la première application que tu ouvres le matin ?",
  "Quel est ton style pour t'habiller un jour normal ?",
  "Quelle est la dernière fois que tu as aidé quelqu'un aujourd'hui ?",
  "Quel est ton moment de solitude préféré dans la journée ?",
  "Quelle est ta petite victoire de la semaine ?",
  "Quel est l'endroit où tu passes le plus de temps chaque jour ?",
  "Quelle est la chose la plus utile que tu as dans ton sac ou tes poches ?",
  "Quel est ton plus grand distrayant pendant que tu travailles ou étudies ?",
  "Quelle est la dernière chose pour laquelle tu as été reconnaissant(e) ?",
  "Quel est ton moment préféré pour appeler ou parler à tes proches ?",
  "Quelle habitude du quotidien tu changerais si tu pouvais ?",
  "Quel est ton petit luxe du quotidien ?",
  "Quelle est la dernière chose qui t'a surpris(e) aujourd'hui ?",
  "Quel est ton mot d'ordre pour bien commencer la journée ?",
  "Quelle est la routine que tu suis religieusement chaque soir ?",
  "Quel est le détail du quotidien que tu ne changerais pour rien au monde ?"
];
